version: "3.2"
services:
  app:
    build: ./facefive
    environment:
      DB_HOST: 'db'
    depends_on:
      - db
    ports:
      - 8080:5000
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'facefive'
      MYSQL_PASSWORD: 'facefivepass'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    restart: always

